import {NextResponse} from "next/server";
import {getAdminFromRequest} from "../../../../../db/admin-auth";
import {activeNewsletterSubscribers,completeNewsletterCampaign,createNewsletterCampaign,getNewsletterCampaign,type NewsletterSubscriber} from "../../../../../db/newsletter";
import {generateNewsletterCampaignCopy} from "../../../../../db/openai";
import {getPublicListings} from "../../../../../db/public-listings";
import {campaignEmailHtml,personalizeUnsubscribe} from "../../../../../db/email-templates";
import {sendSmtpMessages} from "../../../../../db/smtp";

export async function POST(request:Request){if(!(await getAdminFromRequest(request)))return NextResponse.json({error:"Acesso não autorizado."},{status:401});const listings=(await getPublicListings()).filter(item=>item.status==="active"||item.status==="approved").sort((a,b)=>new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime()).slice(0,20);if(!listings.length)return NextResponse.json({error:"Não há anúncios publicados para gerar a campanha."},{status:400});let copy={subject:"20 anúncios da semana no Jornal Balcão",preheader:"Confira uma seleção de anúncios publicados nesta semana.",heading:"Destaques da semana",intro:"Selecionamos anúncios recentes do Jornal Balcão para você consultar em um só lugar."};try{copy=await generateNewsletterCampaignCopy(listings.map(item=>({title:item.title,category:item.category,formattedPrice:item.formattedPrice})));}catch{}const html=campaignEmailHtml(copy,listings);const campaign=await createNewsletterCampaign({...copy,html});return NextResponse.json({campaign});}
export async function PUT(request:Request){if(!(await getAdminFromRequest(request)))return NextResponse.json({error:"Acesso não autorizado."},{status:401});const payload=await request.json().catch(()=>({})) as {id?:string};const campaign=payload.id?await getNewsletterCampaign(payload.id):null;if(!campaign)return NextResponse.json({error:"Campanha não encontrada."},{status:404});if(campaign.status==="sent")return NextResponse.json({error:"Esta campanha já foi enviada."},{status:409});const subscribers=await activeNewsletterSubscribers();if(!subscribers.length)return NextResponse.json({error:"Não há assinantes ativos."},{status:400});try{const result=await sendSmtpMessages(subscribers.map((subscriber:NewsletterSubscriber)=>({to:subscriber.email,subject:campaign.subject,html:personalizeUnsubscribe(campaign.html,subscriber.unsubscribeToken)})));await completeNewsletterCampaign(campaign.id,subscribers.length,result.sent,result.failed);return NextResponse.json({ok:result.failed===0,recipientCount:subscribers.length,...result});}catch{return NextResponse.json({error:"Não foi possível enviar a campanha pelo SMTP configurado."},{status:400});}}
