"use client";
/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */

import { FormEvent, useEffect, useMemo, useState } from "react";
import { PortalHeader } from "../shared";
import { PortalCategory, portalCategories } from "../categories";
import { featuredBenefits, formatPlanPrice, getFeaturedPlans } from "../featured-plans";
import { MapPlaceSearch } from "../google-place-search";

type Photo = { file: File; preview: string };
type Brand = { code: string; name: string; models?: { code: string; name: string }[] };
type VehicleCatalog = Record<"carros" | "motos" | "caminhoes", Brand[]>;
type PagBankEncryptResult = { encryptedCard?: string; hasErrors?: boolean; errors?: Array<{ message?: string }> };
declare global { interface Window { PagSeguro?: { encryptCard: (input: { publicKey: string; holder: string; number: string; expMonth: string; expYear: string; securityCode: string }) => PagBankEncryptResult } } }
const propertyFeatures = ["Piscina", "Varanda", "Área gourmet", "Elevador", "Portaria 24h", "Mobiliado", "Aceita animais", "Ar-condicionado", "Armários planejados", "Acessibilidade"];
const vehicleFeatures = ["Ar-condicionado", "Direção hidráulica", "Vidros elétricos", "Travas elétricas", "Airbag", "ABS", "Câmera de ré", "Sensor de estacionamento", "Banco de couro", "Multimídia", "Controle de estabilidade", "Único dono"];
const negotiations = ["Compra", "Venda", "Troca", "Aluguel", "Temporada", "Serviço", "Outra"];
const propertyTypes = ["Casa", "Apartamento", "Cobertura", "Sítio", "Fazenda", "Terreno", "Loja", "Sala comercial", "Galpão", "Outro"];
const moneyToCents = (value: string) => { const digits = value.replace(/\D/g, ""); return digits ? Number(digits) : null; };
const formatMoney = (value: string) => { const digits = value.replace(/\D/g, "").slice(0, 13); return digits ? (Number(digits) / 100).toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : ""; };
const maskPhone = (value: string) => { const digits = value.replace(/\D/g, "").replace(/^55(?=\d{10,11}$)/, "").slice(0, 11); if (digits.length <= 2) return digits ? `(${digits}` : ""; if (digits.length <= 6) return `(${digits.slice(0, 2)}) ${digits.slice(2)}`; if (digits.length <= 10) return `(${digits.slice(0, 2)}) ${digits.slice(2, 6)}-${digits.slice(6)}`; return `(${digits.slice(0, 2)}) ${digits.slice(2, 7)}-${digits.slice(7)}`; };
type SuccessState = { message: string; listingId: string; qrCodeText?: string; qrCodeImage?: string; paymentExpiresAt?: string; paymentAmountCents?: number; paymentMethod?: "PIX" | "CREDIT_CARD" | null; paymentStatus?: string | null; paymentUnavailable?: boolean; paid?: boolean; cardBrand?: string | null; cardLast4?: string | null; preview: { title: string; category: string; address: string; priceLabel: string; image: string } };

async function readResponse(response: Response) {
  const raw = await response.text();
  if (response.status === 413) return { error: "A imagem ultrapassou o limite de envio. Ela será otimizada; selecione-a novamente e tente publicar." };
  try { return raw ? JSON.parse(raw) as Record<string, unknown> : {}; }
  catch { return { error: response.ok ? "O servidor retornou uma resposta inválida." : raw.slice(0, 180) || "Não foi possível concluir a solicitação." }; }
}

async function optimizeImage(file: File) {
  try {
    const bitmap = await createImageBitmap(file);
    const scale = Math.min(1, 1920 / Math.max(bitmap.width, bitmap.height));
    const canvas = document.createElement("canvas");
    canvas.width = Math.max(1, Math.round(bitmap.width * scale)); canvas.height = Math.max(1, Math.round(bitmap.height * scale));
    canvas.getContext("2d")?.drawImage(bitmap, 0, 0, canvas.width, canvas.height); bitmap.close();
    let quality = .84; let blob: Blob | null = null;
    do { blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/webp", quality)); quality -= .08; } while (blob && blob.size > 1_500_000 && quality >= .52);
    if (!blob) throw new Error("IMAGE_OPTIMIZATION_FAILED");
    return new File([blob], file.name.replace(/\.[^.]+$/, "") + ".webp", { type: "image/webp" });
  } catch {
    if (file.size <= 1_500_000) return file;
    throw new Error(`Não foi possível otimizar a imagem ${file.name}. Use uma imagem JPG, PNG ou WebP menor.`);
  }
}

let pagBankSdkPromise: Promise<void> | null = null;
function loadPagBankSdk() {
  if (window.PagSeguro) return Promise.resolve();
  if (pagBankSdkPromise) return pagBankSdkPromise;
  pagBankSdkPromise = new Promise((resolve, reject) => {
    const existing = document.querySelector<HTMLScriptElement>('script[data-pagbank-sdk="true"]');
    const script = existing || document.createElement("script");
    script.dataset.pagbankSdk = "true"; script.src = "https://assets.pagseguro.com.br/checkout-sdk-js/rc/dist/browser/pagseguro.min.js"; script.async = true;
    script.addEventListener("load", () => window.PagSeguro ? resolve() : reject(new Error("SDK do PagBank indisponível.")), { once: true });
    script.addEventListener("error", () => reject(new Error("Não foi possível carregar a segurança do PagBank.")), { once: true });
    if (!existing) document.head.appendChild(script);
  });
  return pagBankSdkPromise;
}

async function encryptCard(form: FormData) {
  const holder = String(form.get("cardHolder") || "").trim(); const number = String(form.get("cardNumber") || "").replace(/\D/g, "");
  const expMonth = String(form.get("cardExpMonth") || "").replace(/\D/g, ""); const expYear = String(form.get("cardExpYear") || "").replace(/\D/g, ""); const securityCode = String(form.get("cardSecurityCode") || "").replace(/\D/g, "");
  if (holder.length < 3 || number.length < 13 || number.length > 19 || !/^(0?[1-9]|1[0-2])$/.test(expMonth) || expYear.length !== 4 || securityCode.length < 3) throw new Error("Confira o nome, número, validade e código de segurança do cartão.");
  const keyResponse = await fetch("/api/payments/pagbank/public-key", { headers: { Accept: "application/json" } }); const keyData = await readResponse(keyResponse);
  if (!keyResponse.ok || typeof keyData.publicKey !== "string") throw new Error(typeof keyData.error === "string" ? keyData.error : "Não foi possível iniciar o pagamento com cartão.");
  await loadPagBankSdk();
  const result = window.PagSeguro?.encryptCard({ publicKey: keyData.publicKey, holder, number, expMonth: expMonth.padStart(2, "0"), expYear, securityCode });
  if (!result?.encryptedCard || result.hasErrors) throw new Error(result?.errors?.[0]?.message || "Os dados do cartão não foram aceitos.");
  return { encryptedCard: result.encryptedCard, cardHolderName: holder, cardInstallments: Number(form.get("cardInstallments") || 1) };
}

function CardFields({ amountCents }: { amountCents: number }) {
  return <div className="inline-card-fields"><div className="inline-card-heading"><div><strong>Dados do cartão</strong><span>Criptografados no navegador pelo PagBank</span></div><b>{formatPlanPrice(amountCents)}</b></div><div className="listing-fields two"><label className="full">Nome impresso no cartão<input name="cardHolder" autoComplete="cc-name" required placeholder="Nome completo" /></label><label className="full">Número do cartão<input name="cardNumber" inputMode="numeric" autoComplete="cc-number" required maxLength={23} onInput={(event) => { const input = event.currentTarget; input.value = input.value.replace(/\D/g, "").slice(0, 19).replace(/(.{4})/g, "$1 ").trim(); }} placeholder="0000 0000 0000 0000" /></label><label>Mês<input name="cardExpMonth" inputMode="numeric" autoComplete="cc-exp-month" required maxLength={2} placeholder="MM" /></label><label>Ano<input name="cardExpYear" inputMode="numeric" autoComplete="cc-exp-year" required maxLength={4} placeholder="AAAA" /></label><label>Código de segurança<input name="cardSecurityCode" type="password" inputMode="numeric" autoComplete="cc-csc" required maxLength={4} placeholder="CVV" /></label><label>Parcelamento<select name="cardInstallments" defaultValue="1"><option value="1">1x sem juros</option><option value="2">2x</option><option value="3">3x</option></select></label><label className="check full"><input name="saveCard" type="checkbox" />Salvar este cartão com segurança no PagBank</label></div><p className="card-privacy-note">O Portal Balcão guarda apenas o token do PagBank, a bandeira e os quatro últimos dígitos. Número completo e CVV nunca são armazenados.</p></div>;
}

export default function CreateListing() {
  const [categories, setCategories] = useState<PortalCategory[]>(portalCategories);
  const [customer, setCustomer] = useState<{ name: string; whatsapp: string; remainingAds: number } | null>(null);
  const [photos, setPhotos] = useState<Photo[]>([]);
  const [category, setCategory] = useState(""); const [subcategory, setSubcategory] = useState(""); const [negotiation, setNegotiation] = useState("Venda");
  const [features, setFeatures] = useState<string[]>([]); const [attributes, setAttributes] = useState<Record<string, string>>({});
  const [catalog, setCatalog] = useState<VehicleCatalog>({ carros: [], motos: [], caminhoes: [] });
  const [vehicleType, setVehicleType] = useState<keyof VehicleCatalog>("carros"); const [brand, setBrand] = useState("");
  const [price, setPrice] = useState(""); const [rent, setRent] = useState(""); const [iptu, setIptu] = useState(""); const [condo, setCondo] = useState(""); const [negotiable, setNegotiable] = useState(false);
  const [address, setAddress] = useState(""); const [coordinates, setCoordinates] = useState<{ lat: number; lng: number } | null>(null);
  const [mapProvider, setMapProvider] = useState<"google" | "mapbox">("google");
  const [whatsapp, setWhatsapp] = useState("");
  const [publicationType, setPublicationType] = useState<"free" | "featured" | "super_featured">("free"); const [featuredPlan, setFeaturedPlan] = useState("monthly"); const [paymentMethod, setPaymentMethod] = useState<"pix" | "card">("pix");
  const [paymentOptions, setPaymentOptions] = useState({ pix: true, card: true });
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState<SuccessState | null>(null); const [secondsLeft, setSecondsLeft] = useState(0);

  useEffect(() => {
    fetch("/api/customer/me").then(async (response) => { if (!response.ok) { window.location.assign("/entrar?returnTo=%2Fanunciar"); return; } const data = await response.json(); setCustomer(data.customer); setWhatsapp(maskPhone(String(data.customer.whatsapp || ""))); }).catch(() => window.location.assign("/entrar?returnTo=%2Fanunciar"));
    fetch("/api/settings").then((response) => response.json()).then((data) => {
      if (Array.isArray(data.categories) && data.categories.length) setCategories(data.categories);
      const options = { pix: data.pagbank_pix_enabled !== false, card: data.pagbank_card_enabled !== false };
      setPaymentOptions(options); if (!options.pix && options.card) setPaymentMethod("card");
    }).catch(() => undefined);
    fetch("/data/vehicle-catalog.json").then((response) => response.json()).then(setCatalog).catch(() => undefined);
    fetch("/api/maps/config").then((response) => response.json()).then((data) => setMapProvider(data.provider === "mapbox" ? "mapbox" : "google")).catch(() => undefined);
  }, []);
  useEffect(() => () => photos.forEach((photo) => URL.revokeObjectURL(photo.preview)), [photos]);
  useEffect(() => { if (!success?.paymentExpiresAt || success.paid) return; const timer = window.setInterval(() => setSecondsLeft(Math.max(0, Math.floor((new Date(success.paymentExpiresAt!).getTime() - Date.now()) / 1000))), 1000); return () => window.clearInterval(timer); }, [success?.paymentExpiresAt, success?.paid]);
  useEffect(() => { if (!success?.listingId || !success.paymentMethod || success.paid) return; const poll = window.setInterval(async () => { const response = await fetch(`/api/listings/payment-status?id=${encodeURIComponent(success.listingId)}`); const data = await response.json().catch(() => ({})); if (response.ok && data.paid) setSuccess((current) => current ? { ...current, paid: true, message: "Pagamento confirmado. O anúncio foi enviado para revisão." } : current); }, 7000); return () => window.clearInterval(poll); }, [success?.listingId, success?.paymentMethod, success?.paid]);

  const selectedCategory = categories.find((item) => item.name === category);
  const brands = catalog[vehicleType] || [];
  const models = brands.find((item) => item.name === brand)?.models || [];
  const isProperty = category === "Imóveis"; const isVehicle = category === "Veículos";
  const featuredPlans = useMemo(() => getFeaturedPlans(category), [category]);
  const featureOptions = isProperty ? propertyFeatures : isVehicle ? vehicleFeatures : ["Novo", "Usado", "Com garantia", "Entrega disponível", "Nota fiscal", "Aceita troca", "Único dono", "Pronta entrega", "Personalizável", "Atendimento online"];
  const mapSrc = useMemo(() => coordinates ? `/api/maps/embed?lat=${coordinates.lat}&lng=${coordinates.lng}&label=${encodeURIComponent(address || "Local do anúncio")}` : "", [coordinates, address]);

  function addPhotos(files: FileList | null) {
    const incoming = Array.from(files || []).filter((file) => ["image/jpeg", "image/png", "image/webp"].includes(file.type) && file.size <= 8 * 1024 * 1024);
    setPhotos((current) => [...current, ...incoming.map((file) => ({ file, preview: URL.createObjectURL(file) }))].slice(0, 12));
  }
  function removePhoto(index: number) { setPhotos((current) => { URL.revokeObjectURL(current[index].preview); return current.filter((_, itemIndex) => itemIndex !== index); }); }
  function promotePhoto(index: number) { setPhotos((current) => [current[index], ...current.filter((_, itemIndex) => itemIndex !== index)]); }
  function toggleFeature(item: string) { setFeatures((current) => current.includes(item) ? current.filter((value) => value !== item) : [...current, item]); }
  function setAttribute(key: string, value: string) { setAttributes((current) => ({ ...current, [key]: value })); }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError("");
    try {
      if (!coordinates || !address) throw new Error("Selecione um endereço válido na lista de resultados.");
      if (!photos.length) throw new Error("Adicione pelo menos uma foto.");
      const formElement = event.currentTarget; const form = new FormData(formElement);
      const cardPayload = publicationType !== "free" && paymentMethod === "card" ? await encryptCard(form) : {};
      const imageUrls: string[] = [];
      for (const photo of photos) { const optimized = await optimizeImage(photo.file); const upload = new FormData(); upload.append("file", optimized); const response = await fetch("/api/listing-images", { method: "POST", body: upload }); const data = await readResponse(response); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "Falha ao enviar uma foto."); if (typeof data.url !== "string") throw new Error("O endereço da imagem não foi retornado."); imageUrls.push(data.url); }
      const payload = {
        title: form.get("title"), description: form.get("description"), negotiationType: negotiation, category, subcategory,
        priceCents: moneyToCents(price), monthlyRentCents: moneyToCents(rent), iptuCents: moneyToCents(iptu), condoCents: moneyToCents(condo), negotiable,
        address, latitude: coordinates.lat, longitude: coordinates.lng, displayName: form.get("displayName"), whatsapp, images: imageUrls,
        attributes: { ...attributes, videoUrl: String(form.get("videoUrl") || "").trim(), ...(isVehicle ? { vehicleType, brand } : {}) }, features, publicationType, featuredPlan, paymentMethod, saveCard: form.get("saveCard") === "on", ...cardPayload,
      };
      const response = await fetch("/api/listings", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await readResponse(response); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "Não foi possível cadastrar o anúncio.");
      const priceLabel = negotiable ? "Valor a combinar" : negotiation === "Aluguel" ? `R$ ${rent || "0,00"}/mês` : `R$ ${price || "0,00"}`;
      if (typeof data.paymentExpiresAt === "string") setSecondsLeft(Math.max(0, Math.floor((new Date(data.paymentExpiresAt).getTime() - Date.now()) / 1000)));
      setSuccess({ message: String(data.message || "Anúncio salvo."), listingId: String(data.listingId || ""), qrCodeText: typeof data.qrCodeText === "string" ? data.qrCodeText : undefined, qrCodeImage: typeof data.qrCodeImage === "string" ? data.qrCodeImage : undefined, paymentExpiresAt: typeof data.paymentExpiresAt === "string" ? data.paymentExpiresAt : undefined, paymentAmountCents: typeof data.paymentAmountCents === "number" ? data.paymentAmountCents : undefined, paymentMethod: data.paymentMethod === "PIX" || data.paymentMethod === "CREDIT_CARD" ? data.paymentMethod : null, paymentStatus: typeof data.paymentStatus === "string" ? data.paymentStatus : null, paymentUnavailable: data.paymentUnavailable === true, paid: data.paid === true, cardBrand: typeof data.cardBrand === "string" ? data.cardBrand : null, cardLast4: typeof data.cardLast4 === "string" ? data.cardLast4 : null, preview: { title: String(form.get("title") || ""), category, address, priceLabel, image: imageUrls[0] } });
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível cadastrar o anúncio."); } finally { setBusy(false); }
  }

  if (success) return <main><PortalHeader /><section className="listing-success listing-payment-success"><span>{!success.paymentMethod || success.paid ? "✓" : success.paymentStatus === "declined" || success.paymentStatus === "failed" ? "!" : "◷"}</span><h1>{!success.paymentMethod ? "Anúncio cadastrado com sucesso!" : success.paid ? "Pagamento confirmado" : success.paymentMethod === "PIX" ? "Anúncio salvo com sucesso" : success.paymentStatus === "declined" ? "Pagamento não aprovado" : "Pagamento em processamento"}</h1><p>{success.message}</p><article className="listing-confirmation-preview"><img src={success.preview.image} alt="Foto de destaque do anúncio" /><div><small>{success.preview.category}</small><h2>{success.preview.title}</h2><p>{success.preview.address}</p><strong>{success.preview.priceLabel}</strong></div></article>{success.paymentMethod === "PIX" && !success.paymentUnavailable && !success.paid ? <section className="pix-payment-box"><h2>Pagamento via Pix</h2><strong>{formatPlanPrice(success.paymentAmountCents || 0)}</strong>{success.qrCodeImage ? <img src={success.qrCodeImage} alt="QR Code Pix do pagamento" /> : <p>Use o código Pix copia e cola abaixo.</p>}<label>Pix copia e cola<textarea value={success.qrCodeText || ""} readOnly /></label><button type="button" onClick={() => navigator.clipboard.writeText(success.qrCodeText || "")}>Copiar código Pix</button><div className="payment-countdown">Tempo restante: <b>{String(Math.floor(secondsLeft / 60)).padStart(2, "0")}:{String(secondsLeft % 60).padStart(2, "0")}</b></div><small>O status é atualizado automaticamente após a confirmação do PagBank.</small></section> : null}{success.paymentMethod === "CREDIT_CARD" ? <section className={`card-payment-box payment-result ${success.paid ? "paid" : success.paymentStatus === "declined" || success.paymentStatus === "failed" ? "failed" : "pending"}`}><h2>{success.paid ? "Cartão aprovado" : success.paymentStatus === "declined" ? "Cartão não aprovado" : "Processamento do cartão"}</h2><strong>{formatPlanPrice(success.paymentAmountCents || 0)}</strong>{success.cardLast4 ? <p>{success.cardBrand ? `${success.cardBrand.toUpperCase()} · ` : ""}final {success.cardLast4}</p> : null}<p>O registro completo está disponível em Meus Pagamentos.</p></section> : null}<div className="listing-success-actions"><a className="secondary-button" href="/minha-conta/anuncios">Ver anúncio na minha conta</a>{success.paymentMethod ? <a className="primary-button" href="/minha-conta/pagamentos">Meus Pagamentos</a> : <a className="primary-button" href="/anunciar">Cadastrar outro anúncio</a>}</div></section></main>;
  return <main><PortalHeader /><div className="listing-create-shell"><header className="listing-create-head"><h1>Cadastro do anúncio</h1></header>
    <form className="single-listing-form" onSubmit={submit}>
      <section className="listing-section"><div className="listing-section-title"><b>1</b><div><h2>Fotos</h2><p>Adicione até 12 fotos. A primeira será a foto de destaque.</p></div></div><label className="listing-photo-upload">＋<strong>Clique para escolher as imagens</strong><span>JPG, PNG ou WebP · otimizadas automaticamente antes do envio</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => addPhotos(event.target.files)} disabled={photos.length >= 12} /></label><div className="listing-photo-grid">{photos.map((photo, index) => <article key={photo.preview}><img src={photo.preview} alt={`Foto ${index + 1}`} />{index === 0 ? <em>Foto de destaque</em> : <button type="button" onClick={() => promotePhoto(index)}>Definir destaque</button>}<button className="photo-remove" type="button" onClick={() => removePhoto(index)} aria-label="Remover foto">×</button></article>)}</div><small className="listing-count">{photos.length}/12 fotos</small></section>
      <section className="listing-section"><div className="listing-section-title"><b>2</b><div><h2>Categoria e negociação</h2><p>As próximas opções se adaptam ao tipo de anúncio.</p></div></div><div className="listing-fields three"><label>Tipo de negociação<select value={negotiation} onChange={(event) => setNegotiation(event.target.value)} required>{negotiations.map((item) => <option key={item}>{item}</option>)}</select></label><label>Categoria principal<select value={category} onChange={(event) => { setCategory(event.target.value); setSubcategory(""); setFeatures([]); setAttributes({}); }} required><option value="">Selecione</option>{categories.map((item) => <option key={item.name}>{item.name}</option>)}</select></label><label>Subcategoria<select value={subcategory} onChange={(event) => setSubcategory(event.target.value)} required disabled={!selectedCategory}><option value="">Selecione</option>{selectedCategory?.subs.map((item) => <option key={item}>{item}</option>)}</select></label></div></section>
      {isProperty ? <section className="listing-section"><div className="listing-section-title"><b>3</b><div><h2>Dados do imóvel</h2><p>Informe os principais dados para os filtros.</p></div></div><div className="listing-fields four"><label>Tipo do imóvel<select value={attributes.propertyType || ""} onChange={(event) => setAttribute("propertyType", event.target.value)} required><option value="">Selecione</option>{propertyTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label>Quartos<select value={attributes.bedrooms || ""} onChange={(event) => setAttribute("bedrooms", event.target.value)}><option value="">Selecione</option>{["Studio", "1", "2", "3", "4", "5+"] .map((item) => <option key={item}>{item}</option>)}</select></label><label>Banheiros<select value={attributes.bathrooms || ""} onChange={(event) => setAttribute("bathrooms", event.target.value)}><option value="">Selecione</option>{[1,2,3,4,5,6].map((item) => <option key={item}>{item === 6 ? "6+" : item}</option>)}</select></label><label>Vagas de garagem<select value={attributes.parkingSpaces || ""} onChange={(event) => setAttribute("parkingSpaces", event.target.value)}><option value="">Selecione</option>{[0,1,2,3,4,5].map((item) => <option key={item}>{item === 5 ? "5+" : item}</option>)}</select></label><label>Área útil (m²)<input type="number" min="0" value={attributes.area || ""} onChange={(event) => setAttribute("area", event.target.value)} /></label><label>Condição<select value={attributes.condition || ""} onChange={(event) => setAttribute("condition", event.target.value)}><option value="">Selecione</option><option>Novo</option><option>Usado</option><option>Em construção</option></select></label></div></section> : null}
      {isVehicle ? <section className="listing-section"><div className="listing-section-title"><b>3</b><div><h2>Dados do veículo</h2><p>A marca atualiza automaticamente a lista de modelos.</p></div></div><div className="listing-fields four"><label>Tipo<select value={vehicleType} onChange={(event) => { setVehicleType(event.target.value as keyof VehicleCatalog); setBrand(""); setAttribute("model", ""); }}><option value="carros">Carro</option><option value="motos">Moto</option><option value="caminhoes">Caminhão</option></select></label><label>Marca<select value={brand} onChange={(event) => { setBrand(event.target.value); setAttribute("model", ""); }} required><option value="">Selecione</option>{brands.map((item) => <option key={item.code}>{item.name}</option>)}</select></label><label>Modelo<select value={attributes.model || ""} onChange={(event) => setAttribute("model", event.target.value)} required disabled={!brand}><option value="">Selecione</option>{models.map((item) => <option key={item.code}>{item.name}</option>)}</select></label><label>Ano fabricação<input type="number" min="1900" max="2100" value={attributes.year || ""} onChange={(event) => setAttribute("year", event.target.value)} required /></label><label>Ano modelo<input type="number" min="1900" max="2101" value={attributes.modelYear || ""} onChange={(event) => setAttribute("modelYear", event.target.value)} required /></label><label>Portas<select value={attributes.doors || ""} onChange={(event) => setAttribute("doors", event.target.value)}><option value="">Selecione</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label><label>Cor<select value={attributes.color || ""} onChange={(event) => setAttribute("color", event.target.value)}><option value="">Selecione</option>{["Branco","Preto","Prata","Cinza","Vermelho","Azul","Verde","Amarelo","Marrom","Outro"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Câmbio<select value={attributes.transmission || ""} onChange={(event) => setAttribute("transmission", event.target.value)}><option value="">Selecione</option><option>Manual</option><option>Automático</option><option>Automatizado</option><option>CVT</option></select></label><label>Combustível<select value={attributes.fuel || ""} onChange={(event) => setAttribute("fuel", event.target.value)}><option value="">Selecione</option><option>Flex</option><option>Gasolina</option><option>Diesel</option><option>Elétrico</option><option>Híbrido</option><option>GNV</option></select></label><label>Quilometragem<input type="number" min="0" value={attributes.mileage || ""} onChange={(event) => setAttribute("mileage", event.target.value)} /></label></div></section> : null}
      {category ? <section className="listing-section"><div className="listing-section-title"><b>{isProperty || isVehicle ? 4 : 3}</b><div><h2>Opcionais e diferenciais</h2><p>Marque os itens que ajudam o anúncio a aparecer nos filtros.</p></div></div><div className="listing-feature-grid">{featureOptions.map((item) => <label key={item}><input type="checkbox" checked={features.includes(item)} onChange={() => toggleFeature(item)} />{item}</label>)}</div></section> : null}
      <section className="listing-section"><div className="listing-section-title"><b>{isProperty || isVehicle ? 5 : 4}</b><div><h2>Conteúdo e valor</h2><p>Use um título claro e uma descrição completa.</p></div></div><div className="listing-fields two"><label className="full">Título do anúncio<input name="title" required minLength={8} maxLength={120} placeholder="Ex.: Apartamento 3 quartos no Buritis" /></label><label className="full">Descrição<textarea name="description" required minLength={30} maxLength={5000} rows={7} placeholder="Descreva estado, características e condições da negociação" /></label><label className="full">Link do vídeo (opcional)<input name="videoUrl" type="url" inputMode="url" maxLength={500} placeholder="https://www.youtube.com/watch?v=... ou https://site.com/video.mp4" /><small>Compatível com YouTube, Vimeo e arquivos MP4 por HTTPS. O vídeo será exibido no lugar da galeria de fotos.</small></label>{negotiation === "Aluguel" ? <><label>Valor mensal (R$)<input inputMode="numeric" value={rent} onChange={(event) => setRent(formatMoney(event.target.value))} disabled={negotiable} placeholder="0,00" /></label><label>IPTU (R$)<input inputMode="numeric" value={iptu} onChange={(event) => setIptu(formatMoney(event.target.value))} placeholder="0,00" /></label><label>Condomínio (R$)<input inputMode="numeric" value={condo} onChange={(event) => setCondo(formatMoney(event.target.value))} placeholder="0,00" /></label></> : <label>Valor (R$)<input inputMode="numeric" value={price} onChange={(event) => setPrice(formatMoney(event.target.value))} disabled={negotiable} placeholder="0,00" /></label>}<label className="check full"><input type="checkbox" checked={negotiable} onChange={(event) => setNegotiable(event.target.checked)} />Valor a combinar</label></div></section>
      <section className="listing-section"><div className="listing-section-title"><b>{isProperty || isVehicle ? 6 : 5}</b><div><h2>Endereço e mapa</h2><p>Pesquise no {mapProvider === "mapbox" ? "Mapbox" : "Google Maps"} e escolha o endereço correto.</p></div></div><div className="listing-address"><label>Pesquisar endereço<MapPlaceSearch onSelect={(item) => { setAddress(item.formattedAddress); setCoordinates({ lat: item.lat, lng: item.lng }); }} /></label>{address ? <small className="listing-address-selected">{address}</small> : null}{coordinates ? <small className="listing-coordinates">Local selecionado: {coordinates.lat.toFixed(6)}, {coordinates.lng.toFixed(6)}</small> : null}{mapSrc ? <iframe className="listing-map" title="Prévia do mapa" src={mapSrc} loading="lazy" referrerPolicy="no-referrer-when-downgrade" /> : <div className="listing-map-placeholder">A prévia do mapa aparecerá após selecionar o endereço.</div>}</div></section>
      <section className="listing-section"><div className="listing-section-title"><b>{isProperty || isVehicle ? 7 : 6}</b><div><h2>Contato</h2><p>Dados exibidos na página do anúncio.</p></div></div><div className="listing-fields two"><label>Nome de exibição<input name="displayName" defaultValue={customer?.name || ""} required minLength={2} /></label><label>WhatsApp do anúncio<input name="whatsapp" value={whatsapp} onChange={(event) => setWhatsapp(maskPhone(event.target.value))} inputMode="tel" autoComplete="tel" required placeholder="(31) 99999-9999" /></label></div></section>
      <section className="listing-section"><div className="listing-section-title"><b>{isProperty || isVehicle ? 8 : 7}</b><div><h2>Publicação e pagamento</h2><p>Escolha entre anúncio grátis, destacado ou super destacado.</p></div></div><div className="publication-plans three-levels"><label className={publicationType === "free" ? "selected" : ""}><input type="radio" checked={publicationType === "free"} onChange={() => setPublicationType("free")} /><strong>Publicar grátis</strong><span>Publicação com duração de 30 dias.</span><small>O anúncio será revisado pela equipe antes da publicação.</small></label><label className={publicationType === "featured" ? "selected" : ""}><input type="radio" checked={publicationType === "featured"} onChange={() => setPublicationType("featured")} disabled={!paymentOptions.pix && !paymentOptions.card} /><strong>Publicar com destaque</strong><span>Prioridade sobre anúncios grátis.</span><small>Borda vermelha discreta na busca e nas categorias.</small></label><label className={publicationType === "super_featured" ? "selected super" : "super"}><input type="radio" checked={publicationType === "super_featured"} onChange={() => setPublicationType("super_featured")} disabled={!paymentOptions.pix && !paymentOptions.card} /><strong>★ Super destacado</strong><span>Prioridade máxima no portal.</span><small>Home, busca e categorias antes dos demais anúncios.</small></label></div>{publicationType !== "free" ? <><div className="featured-periods">{featuredPlans.map((plan) => <label className={featuredPlan === plan.code ? "selected" : ""} key={plan.code}><input type="radio" checked={featuredPlan === plan.code} onChange={() => setFeaturedPlan(plan.code)} /><span>{plan.label}</span><strong>{formatPlanPrice(plan.amountCents * (publicationType === "super_featured" ? 2 : 1))}</strong><small>{plan.durationLabel}</small><ul>{featuredBenefits.map((benefit) => <li key={benefit}>✓ {benefit}</li>)}</ul></label>)}</div><div className="payment-methods" role="radiogroup" aria-label="Forma de pagamento">{paymentOptions.pix ? <label className={paymentMethod === "pix" ? "selected" : ""}><input type="radio" checked={paymentMethod === "pix"} onChange={() => setPaymentMethod("pix")} />Pix com QR Code</label> : null}{paymentOptions.card ? <label className={paymentMethod === "card" ? "selected" : ""}><input type="radio" checked={paymentMethod === "card"} onChange={() => setPaymentMethod("card")} />Cartão de crédito</label> : null}</div>{paymentMethod === "pix" ? <p className="payment-security-note">Ao continuar, o anúncio será salvo e o QR Code Pix aparecerá logo abaixo para pagamento.</p> : <CardFields amountCents={(featuredPlans.find((plan) => plan.code === featuredPlan)?.amountCents || 0) * (publicationType === "super_featured" ? 2 : 1)} />}</> : null}</section>
      {error ? <div className="listing-error" role="alert">{error}</div> : null}<footer className="listing-submit"><span>Ao publicar, você concorda com os termos de uso do portal.</span><button className="primary-button" disabled={busy || !customer || customer.remainingAds <= 0}>{busy ? publicationType === "free" ? "Publicando anúncio…" : paymentMethod === "card" ? "Processando pagamento…" : "Gerando QR Code…" : publicationType === "free" ? "Publicar anúncio grátis" : paymentMethod === "card" ? "Pagar com cartão" : "Gerar QR Code Pix"}</button></footer>
    </form></div></main>;
}
