"use client";
import {FormEvent,useEffect,useState} from "react";

type CookieChoice={necessary:true;analytics:boolean;marketing:boolean;updatedAt:string};
const COOKIE_KEY="balcao-cookie-consent-v1";const NEWS_KEY="balcao-newsletter-popup-v1";
function readChoice():CookieChoice|null{try{return JSON.parse(localStorage.getItem(COOKIE_KEY)||"null") as CookieChoice|null;}catch{return null;}}

export default function NewsletterExperience(){
  const [newsletterOpen,setNewsletterOpen]=useState(false);const [cookieOpen,setCookieOpen]=useState(false);const [cookieDetails,setCookieDetails]=useState(false);const [choice,setChoice]=useState<CookieChoice|null>(null);const [email,setEmail]=useState("");const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");
  useEffect(()=>{const saved=readChoice();queueMicrotask(()=>{setChoice(saved);setCookieOpen(!saved);});let popup:{at?:number;subscribed?:boolean}|null=null;try{popup=JSON.parse(localStorage.getItem(NEWS_KEY)||"null") as {at?:number;subscribed?:boolean}|null;}catch{}const expired=!popup?.at||Date.now()-Number(popup.at)>14*86400000;if(popup?.subscribed)return;const show=()=>{if(expired)setNewsletterOpen(true);};const timer=window.setTimeout(show,4500);const scroll=()=>{if(window.scrollY+window.innerHeight>=document.documentElement.scrollHeight*.92)show();};const leave=(event:MouseEvent)=>{if(event.clientY<=4)show();};window.addEventListener("scroll",scroll,{passive:true});document.addEventListener("mouseleave",leave);return()=>{clearTimeout(timer);window.removeEventListener("scroll",scroll);document.removeEventListener("mouseleave",leave);};},[]);
  const dismissNewsletter=()=>{setNewsletterOpen(false);localStorage.setItem(NEWS_KEY,JSON.stringify({at:Date.now(),subscribed:false}));};
  const saveCookies=(analytics:boolean,marketing:boolean)=>{const next={necessary:true as const,analytics,marketing,updatedAt:new Date().toISOString()};localStorage.setItem(COOKIE_KEY,JSON.stringify(next));setChoice(next);setCookieOpen(false);setCookieDetails(false);window.dispatchEvent(new CustomEvent("balcao-cookie-consent-changed",{detail:next}));};
  const subscribe=async(event:FormEvent)=>{event.preventDefault();if(!consent)return setStatus("Confirme que deseja receber os anúncios por e-mail.");setBusy(true);setStatus("");const response=await fetch("/api/newsletter/subscribe",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,consent:true,source:"site_popup"})});const data=await response.json().catch(()=>({})) as {error?:string;alreadySubscribed?:boolean;delivered?:boolean};setBusy(false);if(!response.ok)return setStatus(data.error||"Não foi possível concluir o cadastro.");localStorage.setItem(NEWS_KEY,JSON.stringify({at:Date.now(),subscribed:true}));setStatus(data.alreadySubscribed?"Este e-mail já está cadastrado.":data.delivered?"Cadastro concluído. Confira sua caixa de entrada.":"Cadastro concluído com sucesso.");window.setTimeout(()=>setNewsletterOpen(false),2200);};
  return <>
    {newsletterOpen?<div className="newsletter-overlay" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)dismissNewsletter();}}><section className="newsletter-popup" role="dialog" aria-modal="true" aria-labelledby="newsletter-title"><button className="newsletter-close" type="button" onClick={dismissNewsletter} aria-label="Fechar">×</button><div className="newsletter-photo"><picture><source srcSet="/banner-home-classificados.webp" type="image/webp"/><img src="/banner-home-classificados.png" width="1320" height="370" loading="lazy" decoding="async" alt="Anúncios e oportunidades do Jornal Balcão" /></picture></div><form onSubmit={subscribe}><span>Newsletter</span><h2 id="newsletter-title">Seja bem-vindo ao Balcão</h2><p>Faça seu cadastro e receba uma seleção de anúncios e oportunidades do Jornal Balcão por e-mail.</p><label>E-mail<input type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="seuemail@exemplo.com.br" autoComplete="email" required /></label><label className="newsletter-consent"><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)} /><span>Quero receber anúncios e campanhas do Jornal Balcão. Posso cancelar a inscrição a qualquer momento.</span></label><button className="newsletter-submit" disabled={busy}>{busy?"Cadastrando…":"Quero receber os anúncios"}</button>{status?<small role="status">{status}</small>:null}<button className="newsletter-dismiss" type="button" onClick={dismissNewsletter}>Não exibir agora</button></form></section></div>:null}
    <button className="cookie-preferences-button" type="button" onClick={()=>setCookieOpen(true)}>◉ Preferências de cookies</button>
    {cookieOpen?<section className="cookie-panel" role="dialog" aria-modal="false" aria-labelledby="cookie-title"><button className="cookie-close" type="button" onClick={()=>setCookieOpen(false)} aria-label="Fechar">×</button><span>Preferências de cookies</span><h2 id="cookie-title">Sua privacidade no Balcão</h2><p>Usamos cookies necessários para o funcionamento do portal. Analytics e marketing dependem da sua escolha.</p>{cookieDetails?<div className="cookie-options"><label><input type="checkbox" checked disabled /> <span><b>Necessários</b><small>Login, segurança e preferências básicas.</small></span></label><label><input type="checkbox" checked={choice?.analytics||false} onChange={event=>setChoice(current=>({necessary:true,analytics:event.target.checked,marketing:current?.marketing||false,updatedAt:new Date().toISOString()}))} /> <span><b>Analytics</b><small>Medição de acessos e desempenho.</small></span></label><label><input type="checkbox" checked={choice?.marketing||false} onChange={event=>setChoice(current=>({necessary:true,analytics:current?.analytics||false,marketing:event.target.checked,updatedAt:new Date().toISOString()}))} /> <span><b>Marketing</b><small>Publicidade e campanhas personalizadas.</small></span></label></div>:null}<button className="cookie-accept" type="button" onClick={()=>saveCookies(true,true)}>Aceitar todos</button>{cookieDetails?<button className="cookie-secondary" type="button" onClick={()=>saveCookies(Boolean(choice?.analytics),Boolean(choice?.marketing))}>Salvar preferências</button>:<button className="cookie-secondary" type="button" onClick={()=>setCookieDetails(true)}>Personalizar</button>}<button className="cookie-necessary" type="button" onClick={()=>saveCookies(false,false)}>Somente necessários</button></section>:null}
  </>;
}
