/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from "next";
import { PortalFooter, PortalHeader } from "../shared";

export const metadata: Metadata = {
  title: "Lojas Virtuais e Pacotes de Anúncios | Balcão",
  description: "Crie uma loja profissional no Balcão com até 50, 200 ou anúncios ilimitados e integração XML, JSON e sites parceiros.",
};

const plans = [
  { code: "store-free", name: "Loja Essencial", ads: "50 anúncios", price: "Grátis", description: "Para começar a vender com uma vitrine profissional.", features: ["URL profissional", "Logo e perfil da loja", "Cadastro manual em massa", "Página pública da loja"] },
  { code: "store-pro", name: "Loja Profissional", ads: "200 anúncios", price: "R$ 99", period: "/mês", featured: true, description: "Para imobiliárias e lojas com estoque em crescimento.", features: ["Todos os recursos do plano gratuito", "Integração com XML e JSON", "Sincronização por feed", "Suporte a sites parceiros"] },
  { code: "store-unlimited", name: "Loja Ilimitada", ads: "Anúncios ilimitados", price: "R$ 249", period: "/mês", description: "Para operações com grande volume de anúncios.", features: ["Estoque sem limite de anúncios", "XML, JSON e parceiros", "URL profissional e identidade própria", "Prioridade na vitrine de lojas"] },
];

export default function VirtualStoresPage() {
  return <main><PortalHeader /><section className="store-plans-hero"><div><span>Lojas Virtuais Balcão</span><h1>Sua empresa com catálogo próprio e anúncios em escala</h1><p>Escolha um pacote, personalize sua loja e centralize anúncios manuais ou importados por XML, JSON e integrações com sites parceiros.</p><div><a className="primary-button" href="#planos-loja">Escolher plano</a><a className="secondary-button" href="/lojas">Conhecer lojas</a></div></div><aside><strong>Importação inteligente</strong><span>XML</span><span>JSON</span><span>Sites parceiros</span><small>Atualize o estoque com arquivos ou feeds públicos.</small></aside></section><section className="store-benefit-strip"><span><b>✓</b> Logo exclusiva</span><span><b>✓</b> URL profissional</span><span><b>✓</b> Vários anúncios</span><span><b>✓</b> Página pública</span></section><section id="planos-loja" className="store-plans-shell"><header><span>Pacotes de anúncios</span><h2>Um plano para cada fase da operação</h2><p>Todos os planos incluem configuração de loja, identidade própria e gerenciamento pela Minha Conta.</p></header><div className="store-plan-grid">{plans.map((plan) => <article className={plan.featured ? "featured" : ""} key={plan.code}>{plan.featured ? <em>Mais escolhido</em> : null}<span>{plan.name}</span><h3>{plan.ads}</h3><div className="store-plan-price"><strong>{plan.price}</strong><small>{plan.period || "para sempre"}</small></div><p>{plan.description}</p><ul>{plan.features.map((feature) => <li key={feature}>✓ {feature}</li>)}</ul><a className={plan.featured ? "primary-button" : "secondary-button"} href={`/minha-conta/loja?plano=${plan.code}`}>Escolher {plan.name}</a></article>)}</div></section><section className="store-integration-showcase"><div><span>Gestão centralizada</span><h2>Cadastre, importe e publique o estoque da sua empresa</h2><p>A área da loja permite selecionar o tipo da operação, enviar a logo, definir a URL profissional, cadastrar contatos e importar anúncios.</p><ul><li><b>Manual:</b> publique vários anúncios pelo formulário do portal.</li><li><b>XML:</b> envie um arquivo ou sincronize uma URL de feed.</li><li><b>JSON:</b> processe catálogos estruturados de sistemas parceiros.</li><li><b>Parceiros:</b> informe a plataforma e a URL pública de integração.</li></ul><a className="primary-button" href="/minha-conta/loja">Configurar loja virtual</a></div><div className="store-integration-board"><span>Configuração da loja</span><strong>minhaloja.balcão</strong><i>Logo personalizada</i><i>200 anúncios disponíveis</i><i>Feed JSON conectado</i><b>Catálogo pronto para publicar</b></div></section><PortalFooter /></main>;
}
