import { firestoreService } from "./firestore-db";

export const initialSeedData = {
  users: [
    {
      id: 1,
      accountType: "legal",
      taxId: "00000000000191",
      email: "admin@jornalbalcao.com.br",
      name: "Administração Balcão BH",
      whatsapp: "31999990000",
      profileImageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
      isAdmin: true,
      status: "active",
      planCode: "store-unlimited",
      planName: "Plano Administrador Ilimitado",
      adLimit: 9999,
      activeAds: 12,
      verifiedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 2,
      accountType: "legal",
      taxId: "12345678000199",
      email: "vendas@autoshoppingbh.com.br",
      name: "AutoShopping BH Seminovos",
      whatsapp: "31988887777",
      profileImageUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80",
      isAdmin: false,
      status: "active",
      planCode: "store-pro",
      planName: "Plano Loja Pro",
      adLimit: 100,
      activeAds: 4,
      verifiedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 3,
      accountType: "legal",
      taxId: "98765432000188",
      email: "contato@imoveissavassi.com.br",
      name: "Imobiliária Savassi Prime",
      whatsapp: "31999996666",
      profileImageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
      isAdmin: false,
      status: "active",
      planCode: "store-pro",
      planName: "Plano Loja Pro",
      adLimit: 100,
      activeAds: 4,
      verifiedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 4,
      accountType: "physical",
      taxId: "12345678901",
      email: "carlos.silva@gmail.com",
      name: "Carlos Eduardo Silva",
      whatsapp: "31977775555",
      profileImageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
      isAdmin: false,
      status: "active",
      planCode: "free-10",
      planName: "Plano Gratuito 10 Anúncios",
      adLimit: 10,
      activeAds: 2,
      verifiedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 5,
      accountType: "legal",
      taxId: "45678912000133",
      email: "loja@itechbh.com.br",
      name: "iTech Celulares & Informática",
      whatsapp: "31966664444",
      profileImageUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=400&q=80",
      isAdmin: false,
      status: "active",
      planCode: "store-free",
      planName: "Plano Loja Essencial",
      adLimit: 50,
      activeAds: 3,
      verifiedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],

  virtualStores: [
    {
      id: "store-autoshopping",
      userId: 2,
      slug: "autoshopping-bh",
      name: "AutoShopping BH Seminovos",
      type: "vehicle",
      logoUrl: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=400&q=80",
      bannerUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
      primaryColor: "#d71920",
      secondaryColor: "#17191e",
      description: "Concessionária e revenda de seminovos inspecionados com garantia de procedência na Av. Raja Gabáglia em Belo Horizonte.",
      planCode: "store-pro",
      adLimit: 100,
      integrationType: "manual",
      websiteUrl: "https://autoshoppingbh.com.br",
      email: "vendas@autoshoppingbh.com.br",
      phone: "(31) 3333-7777",
      whatsapp: "31988887777",
      socialLinksJson: JSON.stringify({ instagram: "@autoshoppingbh", facebook: "autoshoppingbh" }),
      address: "Av. Raja Gabáglia, 2500 - Estoril",
      city: "Belo Horizonte",
      state: "MG",
      active: true,
      isDemo: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "store-savassi",
      userId: 3,
      slug: "imoveis-savassi",
      name: "Imobiliária Savassi Prime",
      type: "real_estate",
      logoUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=400&q=80",
      bannerUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      primaryColor: "#0f766e",
      secondaryColor: "#111827",
      description: "Especialista em imóveis de alto padrão para venda e locação nas regiões da Savassi, Lourdes, Funcionários e Belvedere em BH.",
      planCode: "store-pro",
      adLimit: 100,
      integrationType: "manual",
      websiteUrl: "https://imoveissavassi.com.br",
      email: "contato@imoveissavassi.com.br",
      phone: "(31) 3222-6666",
      whatsapp: "31999996666",
      socialLinksJson: JSON.stringify({ instagram: "@imoveissavassi", linkedin: "imoveissavassi" }),
      address: "Rua Pernambuco, 1000 - Savassi",
      city: "Belo Horizonte",
      state: "MG",
      active: true,
      isDemo: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "store-itech",
      userId: 5,
      slug: "itech-bh",
      name: "iTech Celulares & Informática",
      type: "general",
      logoUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=400&q=80",
      bannerUrl: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?auto=format&fit=crop&w=1200&q=80",
      primaryColor: "#2563eb",
      secondaryColor: "#0f172a",
      description: "Loja especializada em iPhones, smartphones Android, notebooks, consoles e assistência técnica especializada com garantia.",
      planCode: "store-free",
      adLimit: 50,
      integrationType: "manual",
      websiteUrl: "https://itechbh.com.br",
      email: "loja@itechbh.com.br",
      phone: "(31) 3271-4444",
      whatsapp: "31966664444",
      socialLinksJson: JSON.stringify({ instagram: "@itechbh" }),
      address: "Av. Afonso Pena, 1500 - Centro",
      city: "Belo Horizonte",
      state: "MG",
      active: true,
      isDemo: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],

  listings: [
    {
      id: "anuncio-honda-civic-2023",
      userId: 2,
      title: "Honda Civic Touring 1.5 Turbo 2023 Automático Único Dono",
      description: "Honda Civic Touring 2023, impecável, com apenas 18.000 km rodados. Todas as revisões feitas na concessionária autorizada. Teto solar elétrico, bancos em couro, pacote Honda Sensing completo, carregador por indução e garantia de fábrica.",
      negotiationType: "sell",
      category: "veiculos",
      subcategory: "carros",
      priceCents: 17890000,
      monthlyRentCents: null,
      iptuCents: null,
      condoCents: null,
      negotiable: 0,
      address: "Savassi - Belo Horizonte, MG",
      latitude: "-19.9386",
      longitude: "-43.9344",
      displayName: "AutoShopping BH",
      whatsapp: "31988887777",
      attributesJson: JSON.stringify({
        ano: "2023/2023",
        quilometragem: "18.000 km",
        cambio: "Automático CVT",
        combustivel: "Gasolina",
        cor: "Preto Cristal",
        blindado: "Não",
        portas: "4",
      }),
      featuresJson: JSON.stringify(["Teto Solar", "Piloto Automático Adaptativo", "Câmera 360", "Bancos em Couro", "Sensor de Chuva", "Chave Presencial"]),
      imagesJson: JSON.stringify([
        "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1000&q=80",
        "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1000&q=80",
        "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1000&q=80",
      ]),
      coverImage: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1000&q=80",
      publicationType: "super_featured",
      featuredPlan: "monthly",
      featuredUntil: new Date(Date.now() + 30 * 86400000).toISOString(),
      expiresAt: new Date(Date.now() + 60 * 86400000).toISOString(),
      status: "active",
      paymentProvider: "pagbank",
      paymentStatus: "paid",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "anuncio-toyota-hilux-2022",
      userId: 2,
      title: "Toyota Hilux SRX 2.8 4x4 Turbo Diesel Automática 2022",
      description: "Toyota Hilux SRX 2022 completa com capota marítima, protetor de caçamba, multimídia JBL original, tração 4x4 com reduzida e bloqueio. Carro nunca rodou em terra pesada, revisado e com IPVA pago.",
      negotiationType: "sell",
      category: "veiculos",
      subcategory: "caminhonetes",
      priceCents: 24500000,
      monthlyRentCents: null,
      iptuCents: null,
      condoCents: null,
      negotiable: 0,
      address: "Buritis - Belo Horizonte, MG",
      latitude: "-19.9654",
      longitude: "-43.9678",
      displayName: "AutoShopping BH",
      whatsapp: "31988887777",
      attributesJson: JSON.stringify({
        ano: "2022/2022",
        quilometragem: "35.000 km",
        cambio: "Automático 6 marchas",
        combustivel: "Diesel",
        cor: "Branca Perolizada",
        tracao: "4x4",
      }),
      featuresJson: JSON.stringify(["Tração 4x4", "Som JBL", "Controle de Tração", "Engate Removível", "Bancos Elétricos"]),
      imagesJson: JSON.stringify([
        "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=80",
        "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=80",
      ]),
      coverImage: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=80",
      publicationType: "featured",
      featuredPlan: "monthly",
      featuredUntil: new Date(Date.now() + 30 * 86400000).toISOString(),
      expiresAt: new Date(Date.now() + 60 * 86400000).toISOString(),
      status: "active",
      paymentProvider: "pagbank",
      paymentStatus: "paid",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "anuncio-apto-savassi-3q",
      userId: 3,
      title: "Apartamento 3 Quartos com Suíte e Varanda Gourmet na Savassi",
      description: "Apartamento reformado de 115m² em rua nobre da Savassi. Sala ampla para dois ambientes, varanda integrada com cortina de vidro, 3 quartos com armários planejados (1 suíte máster), cozinha gourmet e 2 vagas de garagem livres e cobertas. Prédio com piscina aquecida, academia e portaria 24h.",
      negotiationType: "sell",
      category: "imoveis",
      subcategory: "apartamentos",
      priceCents: 89000000,
      monthlyRentCents: null,
      iptuCents: 38000,
      condoCents: 85000,
      negotiable: 1,
      address: "Rua Fernandes Tourinho, Savassi - Belo Horizonte, MG",
      latitude: "-19.9392",
      longitude: "-43.9318",
      displayName: "Imobiliária Savassi Prime",
      whatsapp: "31999996666",
      attributesJson: JSON.stringify({
        areaUtil: "115 m²",
        quartos: "3",
        suites: "1",
        banheiros: "3",
        vagas: "2",
        andar: "7º",
      }),
      featuresJson: JSON.stringify(["Piscina Aquecida", "Academia", "Varanda Gourmet", "Portaria 24h", "Salão de Festas", "Elevador"]),
      imagesJson: JSON.stringify([
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
        "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=80",
        "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80",
      ]),
      coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
      publicationType: "super_featured",
      featuredPlan: "monthly",
      featuredUntil: new Date(Date.now() + 30 * 86400000).toISOString(),
      expiresAt: new Date(Date.now() + 90 * 86400000).toISOString(),
      status: "active",
      paymentProvider: "pagbank",
      paymentStatus: "paid",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "anuncio-iphone-15-pro-max",
      userId: 5,
      title: "iPhone 15 Pro Max 256GB Titânio Natural na Caixa com Garantia",
      description: "iPhone 15 Pro Max em estado de zero, sem marcas de uso, saúde da bateria 100%. Acompanha caixa original, cabo USB-C trançado e nota fiscal. Aceitamos seu usado na troca com avaliação imediata.",
      negotiationType: "sell",
      category: "celulares-e-telefonia",
      subcategory: "iphones",
      priceCents: 680000,
      monthlyRentCents: null,
      iptuCents: null,
      condoCents: null,
      negotiable: 0,
      address: "Afonso Pena - Centro, Belo Horizonte, MG",
      latitude: "-19.9208",
      longitude: "-43.9378",
      displayName: "iTech BH",
      whatsapp: "31966664444",
      attributesJson: JSON.stringify({
        marca: "Apple",
        modelo: "iPhone 15 Pro Max",
        capacidade: "256 GB",
        cor: "Titânio Natural",
        condicao: "Seminovo Impecável",
        bateria: "100%",
      }),
      featuresJson: JSON.stringify(["Nota Fiscal", "Garantia 3 Meses", "Caixa Original", "Película de Brinde"]),
      imagesJson: JSON.stringify([
        "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
        "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1000&q=80",
      ]),
      coverImage: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
      publicationType: "featured",
      featuredPlan: "monthly",
      featuredUntil: new Date(Date.now() + 30 * 86400000).toISOString(),
      expiresAt: new Date(Date.now() + 45 * 86400000).toISOString(),
      status: "active",
      paymentProvider: "pagbank",
      paymentStatus: "paid",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "anuncio-projeto-arquitetura",
      userId: 4,
      title: "Projetos de Arquitetura e Reforma Residencial em Belo Horizonte",
      description: "Escritório de arquitetura especializado em projetos residenciais, comerciais e acompanhamento técnico de obras em BH e Nova Lima. Criação de imagens 3D realistas, projetos executivos completos e aprovação em prefeitura.",
      negotiationType: "service",
      category: "servicos",
      subcategory: "arquitetura-e-engenharia",
      priceCents: null,
      monthlyRentCents: null,
      iptuCents: null,
      condoCents: null,
      negotiable: 1,
      address: "Belo Horizonte e Região Metropolitana, MG",
      latitude: "-19.9200",
      longitude: "-43.9400",
      displayName: "Carlos Eduardo Silva Arquitetura",
      whatsapp: "31977775555",
      attributesJson: JSON.stringify({
        atendimento: "Presencial e Online",
        especialidade: "Projetos 3D e Reformas",
        experiencia: "10 anos no mercado mineiro",
      }),
      featuresJson: JSON.stringify(["Visita Técnica Gratuita", "Modelagem 3D", "Acompanhamento de Obra", "RRT Emitida"]),
      imagesJson: JSON.stringify([
        "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1000&q=80",
        "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1000&q=80",
      ]),
      coverImage: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1000&q=80",
      publicationType: "free",
      featuredPlan: null,
      featuredUntil: null,
      expiresAt: new Date(Date.now() + 30 * 86400000).toISOString(),
      status: "active",
      paymentProvider: null,
      paymentStatus: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "anuncio-vaga-dev-fullstack",
      userId: 1,
      title: "Vaga: Desenvolvedor(a) Full Stack TypeScript / React / Node.js",
      description: "Buscamos profissional experiente em React, Next.js e Node.js para atuar no desenvolvimento e evolução de plataformas digitais de alta escala. Regime de contratação PJ ou CLT, modelo híbrido em Belo Horizonte (2 dias presenciais na Savassi) com excelente pacote de benefícios.",
      negotiationType: "job",
      category: "empregos",
      subcategory: "tecnologia-e-ti",
      priceCents: 950000,
      monthlyRentCents: null,
      iptuCents: null,
      condoCents: null,
      negotiable: 1,
      address: "Savassi - Belo Horizonte, MG",
      latitude: "-19.9380",
      longitude: "-43.9350",
      displayName: "Recrutamento & Seleção Balcão",
      whatsapp: "31999990000",
      attributesJson: JSON.stringify({
        nivel: "Pleno / Sênior",
        modalidade: "Híbrido (Savassi, BH)",
        regime: "PJ ou CLT",
        salario: "R$ 9.500,00",
      }),
      featuresJson: JSON.stringify(["Plano de Saúde", "Vale Refeição R$ 1.200", "Bônus Anual", "Auxílio Equipamentos"]),
      imagesJson: JSON.stringify([
        "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1000&q=80",
        "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1000&q=80",
      ]),
      coverImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1000&q=80",
      publicationType: "featured",
      featuredPlan: "monthly",
      featuredUntil: new Date(Date.now() + 30 * 86400000).toISOString(),
      expiresAt: new Date(Date.now() + 30 * 86400000).toISOString(),
      status: "active",
      paymentProvider: "pagbank",
      paymentStatus: "paid",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],

  chatConversations: [
    {
      id: "chat-conv-civic-1",
      listingId: "anuncio-honda-civic-2023",
      listingTitle: "Honda Civic Touring 1.5 Turbo 2023 Automático Único Dono",
      buyerUserId: 4,
      sellerUserId: 2,
      status: "active",
      lastMessageAt: new Date().toISOString(),
      createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "chat-conv-apto-savassi",
      listingId: "anuncio-apto-savassi-3q",
      listingTitle: "Apartamento 3 Quartos com Suíte e Varanda Gourmet na Savassi",
      buyerUserId: 4,
      sellerUserId: 3,
      status: "active",
      lastMessageAt: new Date().toISOString(),
      createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],

  chatMessages: [
    {
      id: "msg-civic-1",
      conversationId: "chat-conv-civic-1",
      senderUserId: 4,
      body: "Olá! Tenho interesse no Civic Touring. O carro ainda está disponível para visita na loja do Estoril?",
      readAt: new Date(Date.now() - 3600000 * 3).toISOString(),
      createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    },
    {
      id: "msg-civic-2",
      conversationId: "chat-conv-civic-1",
      senderUserId: 2,
      body: "Olá, Carlos! Sim, está disponível no nosso showroom na Raja Gabáglia. Quer agendar um test drive para amanhã?",
      readAt: new Date(Date.now() - 3600000 * 2).toISOString(),
      createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    },
    {
      id: "msg-civic-3",
      conversationId: "chat-conv-civic-1",
      senderUserId: 4,
      body: "Perfeito! Posso passar por volta das 14h. Aceitam proposta à vista?",
      readAt: null,
      createdAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    },
    {
      id: "msg-apto-1",
      conversationId: "chat-conv-apto-savassi",
      senderUserId: 4,
      body: "Boa tarde! O apartamento aceita financiamento pela Caixa?",
      readAt: new Date(Date.now() - 3600000 * 18).toISOString(),
      createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    },
    {
      id: "msg-apto-2",
      conversationId: "chat-conv-apto-savassi",
      senderUserId: 3,
      body: "Boa tarde, Carlos! Sim, toda a documentação está 100% regularizada e aceita financiamento por qualquer banco, além de FGTS.",
      readAt: new Date(Date.now() - 3600000 * 12).toISOString(),
      createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    },
  ],

  settings: [
    {
      key: "portal_title",
      value: "Portal de Classificados Balcão - Belo Horizonte",
      updatedAt: new Date().toISOString(),
    },
    {
      key: "portal_whatsapp",
      value: "31999990000",
      updatedAt: new Date().toISOString(),
    },
    {
      key: "portal_contact_email",
      value: "contato@jornalbalcao.com.br",
      updatedAt: new Date().toISOString(),
    },
    {
      key: "featured_plan_price_monthly",
      value: "4990",
      updatedAt: new Date().toISOString(),
    },
    {
      key: "featured_plan_price_quarterly",
      value: "11990",
      updatedAt: new Date().toISOString(),
    },
    {
      key: "featured_plan_price_semiannual",
      value: "19990",
      updatedAt: new Date().toISOString(),
    },
  ],
};

/**
 * Runs migration and seeds the Firestore database if collections are missing or empty.
 */
export async function runFirestoreMigration(force = false) {
  const status = {
    usersMigrated: 0,
    storesMigrated: 0,
    listingsMigrated: 0,
    chatsMigrated: 0,
    messagesMigrated: 0,
    settingsMigrated: 0,
    timestamp: new Date().toISOString(),
    success: true,
  };

  try {
    // 1. Users
    const existingUsers = await firestoreService.list("portal_users", { limitCount: 1 });
    if (!existingUsers.length || force) {
      for (const user of initialSeedData.users) {
        await firestoreService.set("portal_users", user.id, user, true);
        status.usersMigrated++;
      }
    }

    // 2. Stores
    const existingStores = await firestoreService.list("portal_virtual_stores", { limitCount: 1 });
    if (!existingStores.length || force) {
      for (const store of initialSeedData.virtualStores) {
        await firestoreService.set("portal_virtual_stores", store.id, store, true);
        status.storesMigrated++;
      }
    }

    // 3. Listings
    const existingListings = await firestoreService.list("portal_listings", { limitCount: 1 });
    if (!existingListings.length || force) {
      for (const listing of initialSeedData.listings) {
        await firestoreService.set("portal_listings", listing.id, listing, true);
        status.listingsMigrated++;
      }
    }

    // 4. Chats
    const existingChats = await firestoreService.list("portal_chat_conversations", { limitCount: 1 });
    if (!existingChats.length || force) {
      for (const chat of initialSeedData.chatConversations) {
        await firestoreService.set("portal_chat_conversations", chat.id, chat, true);
        status.chatsMigrated++;
      }
      for (const msg of initialSeedData.chatMessages) {
        await firestoreService.set("portal_chat_messages", msg.id, msg, true);
        status.messagesMigrated++;
      }
    }

    // 5. Settings
    const existingSettings = await firestoreService.list("portal_settings", { limitCount: 1 });
    if (!existingSettings.length || force) {
      for (const s of initialSeedData.settings) {
        await firestoreService.set("portal_settings", s.key, s, true);
        status.settingsMigrated++;
      }
    }

    return status;
  } catch (error) {
    console.error("[runFirestoreMigration Error]", error);
    status.success = false;
    return status;
  }
}
