import {NextResponse} from "next/server";
import {getAdminFromRequest} from "../../../../db/admin-auth";
import {deleteNewsletterSubscriber,listNewsletterCampaigns,listNewsletterSubscribers,subscribeNewsletter,type NewsletterSubscriber} from "../../../../db/newsletter";
import {manualEmailHtml,personalizeUnsubscribe} from "../../../../db/email-templates";
import {sendSmtpMessages} from "../../../../db/smtp";

export async function GET(request:Request){if(!(await getAdminFromRequest(request)))return NextResponse.json({error:"Acesso não autorizado."},{status:401});const [subscribers,campaigns]=await Promise.all([listNewsletterSubscribers(),listNewsletterCampaigns()]);return NextResponse.json({subscribers,campaigns},{headers:{"Cache-Control":"no-store"}});}
export async function POST(request:Request){if(!(await getAdminFromRequest(request)))return NextResponse.json({error:"Acesso não autorizado."},{status:401});const payload=await request.json().catch(()=>({})) as {action?:string;email?:string;subject?:string;message?:string};try{if(payload.action==="send-email"){const subscriber=(await listNewsletterSubscribers()).find((item:NewsletterSubscriber)=>item.email===String(payload.email||"").trim().toLowerCase());if(!subscriber)return NextResponse.json({error:"Adicione este e-mail à lista antes de enviar."},{status:400});const subject=String(payload.subject||"").trim();const message=String(payload.message||"").trim();if(!subject||!message)return NextResponse.json({error:"Informe assunto e mensagem."},{status:400});const result=await sendSmtpMessages([{to:subscriber.email,subject,html:personalizeUnsubscribe(manualEmailHtml(message),subscriber.unsubscribeToken)}]);return NextResponse.json({ok:result.sent===1,...result});}const subscriber=await subscribeNewsletter(payload.email||"","admin");return NextResponse.json({ok:true,subscriber});}catch(error){return NextResponse.json({error:error instanceof Error&&error.message==="INVALID_EMAIL"?"Informe um e-mail válido.":"Não foi possível concluir a operação."},{status:400});}}
export async function DELETE(request:Request){if(!(await getAdminFromRequest(request)))return NextResponse.json({error:"Acesso não autorizado."},{status:401});const id=new URL(request.url).searchParams.get("id")||"";if(!id)return NextResponse.json({error:"Assinante inválido."},{status:400});await deleteNewsletterSubscriber(id);return NextResponse.json({ok:true});}
