import {NextResponse} from "next/server";
import {getAdminFromRequest} from "../../../../db/admin-auth";
import {readPrivateSetting,writePortalSettings} from "../../../../db/settings";
import {readSmtpSettings,sendSmtpMessages,validateSmtpSettings} from "../../../../db/smtp";
import {manualEmailHtml} from "../../../../db/email-templates";

export async function GET(request:Request){if(!(await getAdminFromRequest(request)))return NextResponse.json({error:"Acesso não autorizado."},{status:401});const values=await Promise.all(["smtp_host","smtp_port","smtp_secure","smtp_username","smtp_password","smtp_from_name","smtp_from_email","smtp_reply_to"].map(readPrivateSetting));return NextResponse.json({host:values[0]||"",port:Number(values[1]||465),secure:String(values[2]||"true")!=="false",username:values[3]||"",passwordConfigured:Boolean(values[4]),fromName:values[5]||"Jornal Balcão",fromEmail:values[6]||"",replyTo:values[7]||""},{headers:{"Cache-Control":"no-store"}});}
export async function POST(request:Request){if(!(await getAdminFromRequest(request)))return NextResponse.json({error:"Acesso não autorizado."},{status:401});const payload=await request.json().catch(()=>({})) as Record<string,unknown>;const current=await readSmtpSettings();const next={...current,host:String(payload.host||current.host).trim(),port:Number(payload.port||current.port),secure:payload.secure!==false,username:String(payload.username||current.username).trim(),password:typeof payload.password==="string"&&payload.password.trim()?payload.password:current.password,fromName:String(payload.fromName||current.fromName||"Jornal Balcão").trim(),fromEmail:String(payload.fromEmail||current.fromEmail).trim().toLowerCase(),replyTo:String(payload.replyTo||"").trim().toLowerCase()};try{validateSmtpSettings(next);}catch(error){const code=error instanceof Error?error.message:"";return NextResponse.json({error:code==="SMTP_PORT_25_BLOCKED"?"A porta 25 não é permitida. Use 465, 587 ou 2525.":"Preencha host, usuário, senha e remetente SMTP."},{status:400});}await writePortalSettings({smtp_host:next.host,smtp_port:next.port,smtp_secure:next.secure,smtp_username:next.username,smtp_password:next.password,smtp_from_name:next.fromName,smtp_from_email:next.fromEmail,smtp_reply_to:next.replyTo});return NextResponse.json({ok:true});}
export async function PUT(request:Request){if(!(await getAdminFromRequest(request)))return NextResponse.json({error:"Acesso não autorizado."},{status:401});const payload=await request.json().catch(()=>({})) as Record<string,unknown>;const email=String(payload.testEmail||"").trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email))return NextResponse.json({error:"Informe um e-mail válido para o teste."},{status:400});try{const result=await sendSmtpMessages([{to:email,subject:"Teste SMTP — Jornal Balcão",html:manualEmailHtml("A integração SMTP do Jornal Balcão está funcionando corretamente.")}],{host:String(payload.host||"")||undefined,port:Number(payload.port||0)||undefined,secure:payload.secure!==false,username:String(payload.username||"")||undefined,password:String(payload.password||"")||undefined,fromName:String(payload.fromName||"")||undefined,fromEmail:String(payload.fromEmail||"")||undefined,replyTo:String(payload.replyTo||"")||undefined});if(!result.sent)throw new Error("SMTP_SEND_FAILED");return NextResponse.json({ok:true});}catch(error){return NextResponse.json({error:error instanceof Error&&error.message.includes("SMTP_NOT_CONFIGURED")?"Salve ou informe todos os dados SMTP antes do teste.":"O servidor SMTP não aceitou o envio. Verifique host, porta, TLS, usuário e senha."},{status:400});}}
