import type { PublicListing } from "./public-listings";
import { SITE_URL } from "../lib/site-url";

function escapeHtml(value:string){return value.replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]||char));}
function absolute(value:string|null|undefined){if(!value)return `${SITE_URL}/logo-balcao.jpg`;try{return new URL(value,SITE_URL).toString();}catch{return `${SITE_URL}/logo-balcao.jpg`;}}
function frame(content:string,preheader:string){return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Jornal Balcão</title></head><body style="margin:0;background:#f3f4f6;font-family:Poppins,Arial,sans-serif;color:#20242a"><span style="display:none;max-height:0;overflow:hidden;opacity:0">${escapeHtml(preheader)}</span><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f3f4f6"><tr><td align="center" style="padding:24px 10px"><table role="presentation" width="680" cellspacing="0" cellpadding="0" style="width:100%;max-width:680px;background:#fff;border-radius:14px;overflow:hidden"><tr><td style="padding:22px 28px;border-bottom:3px solid #d71920"><img src="${SITE_URL}/logo-balcao.jpg" width="190" alt="Jornal Balcão" style="display:block;max-width:100%;height:auto"></td></tr><tr><td style="padding:30px 28px">${content}</td></tr><tr><td style="padding:22px 28px;background:#17191e;color:#c8cbd0;font-size:12px;line-height:1.6">Jornal Balcão · Anunciou, vendeu.<br><a href="{{unsubscribe_url}}" style="color:#fff">Cancelar inscrição</a></td></tr></table></td></tr></table></body></html>`;}

export function welcomeEmailHtml(copy:{heading:string;intro:string;cta:string}){return frame(`<h1 style="margin:0 0 14px;font-size:30px;line-height:1.15">${escapeHtml(copy.heading)}</h1><p style="margin:0 0 24px;color:#5d6570;font-size:16px;line-height:1.65">${escapeHtml(copy.intro)}</p><a href="${SITE_URL}/anuncios" style="display:inline-block;padding:13px 20px;border-radius:8px;background:#d71920;color:#fff;text-decoration:none;font-weight:700">${escapeHtml(copy.cta)}</a>`,`Novidades e oportunidades do Jornal Balcão.`);}

export function campaignEmailHtml(copy:{preheader:string;heading:string;intro:string},listings:PublicListing[]){const rows=[] as string[];for(let index=0;index<listings.length;index+=2){const cells=listings.slice(index,index+2).map(item=>`<td width="50%" valign="top" style="padding:8px"><a href="${absolute(item.url)}" style="color:#20242a;text-decoration:none"><img src="${absolute(item.coverImage)}" width="290" alt="" style="display:block;width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:9px"><span style="display:block;margin-top:8px;color:#d71920;font-size:10px;font-weight:700;text-transform:uppercase">${escapeHtml(item.category)}</span><strong style="display:block;margin:5px 0;font-size:15px;line-height:1.35">${escapeHtml(item.title)}</strong><b style="font-size:17px">${escapeHtml(item.formattedPrice)}</b></a></td>`).join("");rows.push(`<tr>${cells}${index+1===listings.length?'<td width="50%"></td>':""}</tr>`);}return frame(`<h1 style="margin:0 0 12px;font-size:30px;line-height:1.15">${escapeHtml(copy.heading)}</h1><p style="margin:0 0 22px;color:#5d6570;font-size:15px;line-height:1.6">${escapeHtml(copy.intro)}</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0">${rows.join("")}</table><p style="margin:26px 0 0;text-align:center"><a href="${SITE_URL}/anuncios" style="display:inline-block;padding:13px 22px;border-radius:8px;background:#d71920;color:#fff;text-decoration:none;font-weight:700">Ver todos os anúncios</a></p>`,copy.preheader);}

export function manualEmailHtml(message:string){return frame(`<h1 style="margin:0 0 14px;font-size:28px">Notícias do Jornal Balcão</h1><div style="color:#4f5864;font-size:15px;line-height:1.7">${escapeHtml(message).replace(/\n/g,"<br>")}</div>`,`Mensagem do Jornal Balcão.`);}

export function personalizeUnsubscribe(html:string,token:string){return html.replaceAll("{{unsubscribe_url}}",`${SITE_URL}/api/newsletter/unsubscribe?token=${encodeURIComponent(token)}`);}
